from tkinter import *

root = Tk()
def New():
    print("New file created")
def undo():
    print("clicked Undo")
def redo():
    print("clicked Redo")

mymenu = Menu(root)

root.config(menu=mymenu)

submenu1 = Menu(mymenu)
mymenu.add_cascade(label="File",menu=submenu1)
submenu1.add_command(label="New Text File")
submenu1.add_command(label="New File", command=New)
submenu1.add_command(label="New Window")
submenu1.add_separator()
submenu1.add_command(label="Open File")
submenu1.add_command(label="Open Folder")
submenu1.add_command(label="Open Workspace")
submenu1.add_separator()
submenu1.add_command(label="Exit" ,command=root.quit)
submenu2 = Menu(mymenu)
mymenu.add_cascade(label="Edit",menu=submenu2)
submenu2.add_command(label="Undo",command=undo)
submenu2.add_command(label="Redo",command=redo)
submenu2.add_separator()
submenu2.add_command(label="Cut")
submenu2.add_command(label="Copy")
submenu2.add_command(label="Paste")
submenu2.add_separator()
submenu2.add_command(label="Find")
submenu2.add_command(label="Replace")
submenu3 = Menu(mymenu)
mymenu.add_cascade(label="View",menu=submenu3)
submenu3.add_command(label="Command Palette")
submenu3.add_command(label="Open View")
submenu3.add_separator()
submenu3.add_command(label="Appearance")
submenu3.add_command(label="Edit Layout")
submenu3.add_separator()
submenu3.add_command(label="Search")
submenu3.add_command(label="Run")
submenu3.add_command(label="Extension")
submenu4 = Menu(mymenu)
mymenu.add_cascade(label="Go",menu=submenu4)
submenu4.add_command(label="Back")
submenu4.add_command(label="Forward")
submenu4.add_command(label="Last Edited")
submenu4.add_separator()
submenu4.add_command(label="Switch Editor")
submenu4.add_command(label="Switch Group")
submenu4.add_separator()
submenu4.add_command(label="Go To File")
submenu5 = Menu(mymenu)
mymenu.add_cascade(label="Terminal",menu=submenu5)
submenu5.add_command(label="New Terminal")
submenu5.add_command(label="Split Terminal")
submenu5.add_separator()
submenu5.add_cascade(label="Run Task")
submenu5.add_cascade(label="Run Build Task")
submenu5.add_cascade(label="Run Active File")
submenu5.add_cascade(label="Run Selected Task")


root.mainloop()